### ISSUE TITLE
[Docs]: Document how to configure nested stream maps values with environment variables in Meltano

### ISSUE THREAD

**Issue by edgarrmondragon** [meltano/sdk#1073]
### Documentation type

How-to guides

### Description

Example adapted from the [`meltano-map-transform` README](https://github.com/MeltanoLabs/meltano-map-transform/#meltano-installation-instructions):

```yaml
plugins:
  extractors:
  - name: tap-csv
    variant: meltanolabs
    pip_url: git+https://github.com/MeltanoLabs/tap-csv.git
    settings:
    - name: stream_maps.customers.email
    - name: stream_maps.customers.email_domain
    - name: stream_maps.customers.email_hash
    - name: stream_maps.customers.__else__
    - name: stream_maps.stream_map_config
    # Note that these don't work: https://github.com/meltano/meltano/issues/6382
    config:
      stream_maps.customers.email: null
      stream_maps.customers.__else__: null
```

```env
TAP_CSV_STREAM_MAPS_CUSTOMERS_EMAIL_DOMAIN='email.split("@")[-1]'
TAP_CSV_STREAM_MAPS_CUSTOMERS_EMAIL_HASH='md5(config["hash_seed"] + email)'
TAP_CSV_STREAM_MAP_CONFIG_HASH_SEED='01AWZh7A6DzGm6iJZZ2T'
```
