### ISSUE TITLE
feat: standardise per-stream config approach

### ISSUE THREAD

**Issue by kgpayne** [meltano/sdk#1350]
### Feature scope

Configuration (settings parsing, validation, etc.)

### Description

We have at least two open issues for features requiring per-stream configuration:

- #1240
- #1333

It strikes me that we may want to standardise our approach for specifying per-stream config, and leverage the same pattern-matching functions for all per-stream config. Something like:

```yaml
# config in yaml for readability
config:
  start_date: "2010-01-01T00:00:00Z"
  streams:
    "*":
      ignore: true
    "my_stream_name":
      ignore: false
      max_records_limit: 1000
    "some_stream_prefix_*":
      ignore: false
```

The above would have the following effect:
- ignore/exclude all streams
- explicitly include stream "my_stream_name", setting its `max_records_limit` to 1000
- explicitly include streams beginning with "some_stream_prefix_"

**Comment by kgpayne** [comment]
@aaronsteers @pnadolny13 FYI as you opened those two issues 🙂

**Comment by pnadolny13** [comment]
@kgpayne I like this idea!

One thing to consider though is how to cleanly override these settings. For me I like to set the streams in the base plugin configuration so theyre shared by all environments, then override a config settings like `max_records_limit` in the environment config i.e. the cicd environment. The way that it seems meltano works right now is that if I add select criteria to an environment it treated as "instead" vs "in addition to", so theres no way to say "keep my base selection criteria but also add this extra `max_records_limit` setting to each".

So the challenge I see with the approach you suggested is that if I have complex stream selection at the base level then I need to copy/paste it into my environment config to keep the same stream config but override the `max_records_limit` (see example below). For me I'm hestitant to do that because I risk having my stream selection in non-prod environments differ from prod. Does that make sense?

I'm not sure what the solution is though, maybe having a way to treat environment select criteria as additional criteria. In a lot of implementations we had ways to manipulate selection in the catalog.json and config.json, so the config could be used in meltano environments to achieve this goal.

Here's an example of what I'm trying to describe. To keep the same selection criteria and add `max_records_limit` I need to copy/paste it.

```
plugins:
  extractors:
  - name: tap-gitlab
    variant: meltanolabs
    pip_url: git+https://github.com/pnadolny13/tap-gitlab.git@author_usernames
    select:
      projects.*:
      merge_requests.*:
      issues.*:
      '!issues.description':
      '!issues.title':
      '!merge_requests.description':
      '!merge_requests.title':
environments:
- name: userdev
  config:
    plugins:
      extractors:
      - name: tap-gitlab
        config:
          groups: meltano
          start_date: '2020-01-01T00:00:00Z'
        select:
          projects.*:
            max_records_limit: 1000
          merge_requests.*:
            max_records_limit: 1000
          issues.*:
            max_records_limit: 1000
          '!issues.description':
            max_records_limit: 1000
          '!issues.title':
            max_records_limit: 1000
          '!merge_requests.description':
            max_records_limit: 1000
          '!merge_requests.title':
            max_records_limit: 1000
```

On the other hand something like this would end up ignoring all the selection rules defined and overriding them with *.

```
plugins:
  extractors:
  - name: tap-gitlab
    variant: meltanolabs
    pip_url: git+https://github.com/pnadolny13/tap-gitlab.git@author_usernames
    select:
      projects.*:
      merge_requests.*:
      issues.*:
      '!issues.description':
      '!issues.title':
      '!merge_requests.description':
      '!merge_requests.title':
environments:
- name: userdev
  config:
    plugins:
      extractors:
      - name: tap-gitlab
        config:
          groups: meltano
          start_date: '2020-01-01T00:00:00Z'
        select:
          '*':
            max_records_limit: 1000
```

**Comment by kgpayne** [comment]
@pnadolny13 thanks for your feedback 🙌 Just to clarify - this would be a new config option in the `sdk`, not a change to the `select` feature in Meltano (though the two _look_ and behave quite similarly). Therefore these options would fall under the `config` part of your Meltano examples, not `select`. I.e.

```yaml
plugins:
  extractors:
  - name: tap-gitlab
    variant: meltanolabs
    pip_url: git+https://github.com/meltanolabs/tap-gitlab.git
    select:
      # rules as normal
    config:
      streams:
        "*":
          ignore: true
environments:
- name: userdev
  config:
    plugins:
      extractors:
      - name: tap-gitlab
        config:
          groups: meltano
          start_date: '2020-01-01T00:00:00Z'
          streams:
            "*":
              max_records_limit: 100
            "my_selected_stream_prefix_*":
              ignore: false
```

So I would _expect_ Meltano to do a merge in the example above, with the resulting config for `userdev` being:

```yaml
config:
  groups: meltano
  start_date: '2020-01-01T00:00:00Z'
  streams:
    "*":
      ignore: true
      max_records_limit: 100
    "my_selected_stream_prefix_*":
      ignore: false
```
This is maybe still somewhat confusing in that `"my_selected_stream_prefix_*"` streams would inherit `max_records_limit: 100` from `"*"`, but I think that is what most people would expect the behaviour to be 😅

I know this also raises questions about the _use_ of `ignore` in config vs. selection in Meltano, which @aaronsteers covers well in the issue for the `ignore` feature #1240 🙂
