### ISSUE TITLE
Migrate cookiecutters to Ruff for linting

### ISSUE THREAD

**Issue by aaronsteers** [meltano/sdk#1596]
> **Note**
> Caveat: this is admittedly low pri. Logging here just because it's been on my mind recently.

We're seeing a great improvement to overall DX by using Ruff now in Meltano, SDK, and other repos we maintain.

It seems like it could be a nice improvement to add Ruff lint rules and migrate off the other tools like `tox`, `flake8`, etc.

One thing to answer first, perhaps, is a guide for "best practice" config options in Ruff. 

Do we have an existing MeltanoLabs tap or target that we think has a good configset to use as generalizable defaults?

cc @edgarrmondragon  for your thoughts.

**Comment by edgarrmondragon** [comment]
I most recently added Ruff to [MeltanoLabs/tap-stackexchange](https://github.com/MeltanoLabs/tap-stackexchange) with the following config:

```toml
[tool.ruff]
ignore = [
    "ANN101",  # missing-type-self
]
select = ["ALL"]
target-version = "py37"

[tool.ruff.flake8-annotations]
allow-star-arg-any = true

[tool.ruff.pydocstyle]
convention = "google"
```

1. The `ALL` code selects all Ruff rules. Most taps are simple enough that they shouldn't require a large effort to make them pass all checks.
2. Ignored rules should have a comment with their human-friendly name.
3. `target-version` is the minimum Python supported.
4. `allow-star-arg-any` allows annotating `def my_func(*args: Any, **kwargs: Any): ...`.
