### ISSUE TITLE
bug: Mapped datetime values are typed as strings in the schema message

### ISSUE THREAD

**Issue by edgarrmondragon** [meltano/sdk#1695]
### Singer SDK Version

0.26.0

### Is this a regression?

- [ ] Yes

### Python Version

NA

### Bug scope

Mapping (stream maps, flattening, etc.)

### Operating System

NA

### Description

When generating a datetime value from a string using stream map functionality, e.g.

```yaml
stream_maps:
  my_stream:
    created: datetime.datetime.from_timestamp(createdAt)
```

the detected schema type for the value falls back to string.

https://github.com/meltano/sdk/blob/33d64c8dc94d039368bee16da6ab0037e6672ff6/singer_sdk/mapper.py#L372-L379
