### ISSUE TITLE
feat(templates): Add optional dynamic versioning to generated projects

### ISSUE THREAD

**Issue by edgarrmondragon** [meltano/sdk#1717]
### Feature scope

Other

### Description

When the user chooses to use dynamic versioning (the default), we add the following to `pyproject.toml`:

```toml
[tool.poetry-dynamic-versioning]
enable = true

[build-system]
requires = ["poetry-core>=1.0.0", "poetry-dynamic-versioning"]
build-backend = "poetry_dynamic_versioning.backend"
```
