### ISSUE TITLE
Additional Metadata for PyPI

### ISSUE THREAD

**Issue by MeltyBot** [meltano/sdk#174]
Migrated from GitLab: https://gitlab.com/meltano/sdk/-/issues/175

Originally created by @edgarrmondragon on 2021-07-30 22:16:19

---

## Summary

Add more project metadata fields for PyPI.

## Proposed benefits
[//]: # (Concisely summarize the benefits this feature would bring to yourself and other users.)

- More resource links in our PyPI page (looks a bit naked atm): https://pypi.org/project/singer-sdk/
- Better SourceRank score: https://libraries.io/pypi/singer-sdk/sourcerank

## Proposal details
[//]: # (In as much detail as you are able, describe the feature you'd like to build or would like to see built.)

[According to the Poetry docs](https://python-poetry.org/docs/pyproject/), we seem to be missing a few optional metadata fields:

- `maintainers`
- `readme` (i.e. `README.md`)
- `homepage` (https://sdk.meltano.com/en/latest/)
- `repository` (https://gitlab.com/meltano/sdk)
- `documentation` (https://sdk.meltano.com/en/latest/)
- `keywords`
- `classifiers`. These may be more relevant for plugins built with the SDK so they can be grouped. For example [the Django 3.2 classifier](https://pypi.org/search/?c=Framework+'Reference to deleted milestone 3'A%3A+Django+'Reference to deleted milestone 3'A%3A+3.2) has plugins compatible with that version.

We can also [add custom URLs](https://python-poetry.org/docs/pyproject/#urls):

```toml
[tool.poetry.urls]
"Issue Tracker" = "https://gitlab.com/meltano/sdk/-/issues"
"Twitter" = "https://twitter.com/meltanodata/"
"Changelog" = "https://gitlab.com/meltano/sdk/-/blob/main/CHANGELOG.md"
"Slack" = "https://join.slack.com/t/meltano/shared_invite/zt-obgpdeba-7yrqKhwyMBfdHDXsZY8G7Q"
"GitHub Mirror" = "https://github.com/meltano/sdk"
"Youtube" = "https://www.youtube.com/meltano"
```

## Best reasons not to build
[//]: # (Will this negatively affect any existing functionality? Do you anticipate any breaking changes versus what may already be working today? Make the counter-argument to your proposal here.)

None that I can think of.

A similar issue for Meltano is https://gitlab.com/meltano/meltano/-/issues/2874.
