### ISSUE TITLE
feat(mappers): Allow developers to specify a JSON schema for mapped properties

### ISSUE THREAD

**Issue by edgarrmondragon** [meltano/sdk#2010]
### Feature scope

Taps (catalog, state, stream maps, tests, etc.)

### Description

Currently, developers have to wrap properties in type hints for the SDK to map properties to the corresponding JSON schema type:

https://github.com/meltano/sdk/blob/2dc27fc6e8973f067f32dcc5fdbb7cfef1bf0e3d/singer_sdk/mapper.py#L365-L375

It would be a better DX for developers to be able to set the type explicitly.

## Proposal

```yaml
stream_maps:
  # Apply these transforms to the stream called 'customers'
  customers:
    email: __NULL__
    email_domain: owner_email.split('@')[-1]
    email_hash: md5(config['hash_seed'] + owner_email)
    # Without specifying a type, the SDK will map this incorrectly to a String type
    is_gmail: "'@gmail.com' in owner_email"
    __else__: null
    __schema__:
      is_gmail:
        type: bool
stream_map_config:
  # hash outputs are not able to be replicated without the original seed:
  hash_seed: 01AWZh7A6DzGm6iJZZ2T
```

**Comment by haleemur** [comment]
@edgarrmondragon thank you for writing the proposal.

I'm curious to hear how you feel about this alternative:

```
stream_maps:
  # Apply these transforms to the stream called 'customers'
  customers:
    email: __NULL__
    email_domain: 
      expr: owner_email.split('@')[-1]
      type: [string]
    email_hash: 
      expr: md5(config['hash_seed'] + owner_email)
      type: [string]
    # Without specifying a type, the SDK will map this incorrectly to a String type
    is_gmail: "'@gmail.com' in owner_email"
    __else__: null

stream_map_config:
  # hash outputs are not able to be replicated without the original seed:
  hash_seed: 01AWZh7A6DzGm6iJZZ2T
```

the new field is defined by `(fieldname, __NULL__ | expr-string | typed-expr-obj)`, where `typed-expr-obj` is an object with type `{expr: string, type: json-schema-type}`

`jsonschema` is widely used within meltano, the community will already be familiar with it, and this will allow developers to provide compound type information out of the box.

I think placing the schema next to the property definition may make it easy to spot any errors during development
