### ISSUE TITLE
bug: activate_version deletes rows inserted in earlier batches (and deletes despite hard_delete not being set)

### ISSUE THREAD

**Issue by msg555** [meltano/sdk#2103]
### Singer SDK Version

0.30.0

### Is this a regression?

- [ ] Yes

### Python Version

3.9

### Bug scope

Targets (data type handling, batching, SQL object generation, etc.)

### Operating System

Linux

### Description

I was attempting to transition to using meltanolabs-target-snowflake (version 0.5.1) from the pipelinewise variant.

When I run EL from a tap_mysql (pipelinewise-tap-mysql) to this target on a table that has 21k rows, I find that after EL completes the destination table only has 1k rows instead. If I turn off `hard_delete` I instead end up with the full 21k rows. From some investigation it appears that this code snippet is the problem: https://github.com/meltano/sdk/blob/299acc046990db9b2e3d68a9bb8a72eb73511857/singer_sdk/sinks/sql.py#L381-L389

I see two problems here:

- This seems to be defaulting to hard_delete being enabled, which is not the documented default
- This is deleting rows with the current version, should this be < instead of <=? That would seem to agree with the soft delete logic below this.

Proposed patch might look like

```py
        if self.config.get("hard_delete", False):
            with self.connector._connect() as conn, conn.begin():  # noqa: SLF001
                conn.execute(
                    sqlalchemy.text(
                        f"DELETE FROM {self.full_table_name} "  # noqa: S608
                        f"WHERE {self.version_column_name} < {new_version}",
                    ),
                )
            return
```

Loader config

```yaml
    - name: target-snowflake
      variant: meltano
      config:
        account: ${TARGET_SNOWFLAKE_ACCOUNT}
        user: ${TARGET_SNOWFLAKE_USER}
        password: ${TARGET_SNOWFLAKE_PASSWORD}
        database: MY_DATABASE
        default_target_schema: MY_SCEHMA
        warehouse: MY_WAREHOUSE
        add_record_metadata: true
```
