### ISSUE TITLE
bug: parsing ObjectId object from MongoDB in tap-mongodb

### ISSUE THREAD

**Issue by dgawlowsky** [meltano/sdk#2202]
### Singer SDK Version

0.31.1

### Is this a regression?

- [ ] Yes

### Python Version

3.8

### Bug scope

Taps (catalog, state, etc.)

### Operating System

MacOS

### Description

When using `tap-mongodb` to extract the data from Amazon DocumentDB I encounter the following error

```
[error    ] Extraction failed              code=1 message=TypeError: Object of type ObjectId is not JSON serializable name=meltano run_id=8ecfabdc-ab96-4195-9f6e-137988dc3b0e state_id=2024-01-30T215143--tap-mongodb--target-s3
```

Config I am using in `meltano.yml`:

```
plugins:
  extractors:
  - name: tap-mongodb
    variant: meltanolabs
    pip_url: git+https://github.com/MeltanoLabs/tap-mongodb.git
    config:
      allow_modify_change_streams: true
      flattening_enabled: true
      flattening_max_depth: 1
            
    metadata:
      '*':
        replication-key: replication_key
        replication-method: INCREMENTAL
```

The error can be traced back to the _flatten_record function from `singer_sdk` library -  more precisely this file: /Users/x/projects/z/y/.meltano/extractors/tap-mongodb/venv/lib/python3.8/site-packages/singer_sdk/helpers/_flattening.py

I noticed I can fix it by replacing `json.dumps(v)` in `_flatten_record` function to `dumps(v)` which would come from `bson` library `from bson.json_util import dumps`. 

Would you accept such fix or are there other conditions / scenarios I should take into account?
