### ISSUE TITLE
bug: property-level aliases/renaming doesn't appear to work

### ISSUE THREAD

**Issue by kcphila** [meltano/sdk#2545]
### Meltano Version

3.0.0

### Python Version

3.10

### Bug scope

CLI (options, error messages, logging, etc.)

### Operating System

Linux - 20.04

### Description

Multiple core docs specify that properties can be renamed with mappers:
- The [`meltano mappers guide` documentation](https://docs.meltano.com/guide/mappers/) indicates, in the **Property (Column) Level**, section, that `Aliasing: properties can be renamed in the resulting stream e.g. altering a column name from id -> customer_id`
- The [Meltano SDK stream_maps documentation](https://sdk.meltano.com/en/latest/stream_maps.html), in the **Property-Level Mapping Applications** section, indicate that stream_maps support `Property-level aliasing: properties can be renamed in the resulting stream.` 

However, in v3.0.0, either this no longer works or all documentation that provides examples have been lost, as I searched through the docs as well as the source code for both the SDK and the `meltano-map-transform` plugin.

For example, for a config file that looks like :

```yaml
...
  mappers:
  - name: meltano-map-transformer
    variant: meltano
    pip_url: git+https://github.com/MeltanoLabs/meltano-map-transform.git
    mappings:
    - name: lower-case-schema
      config:
        stream_maps:
          {STREAM_NAME}:
            __alias__: {new-table-name}
            {COLUMN-PROPERTY}:
              __alias__: {new-property-name}
...
```

The stream/table name is renamed but the property/column is not. There is a partial work around to make a copy of the column and then delete the old column.

```yaml
      config:
        stream_maps:
          {STREAM_NAME}:
            __alias__: {new-table-name}
            {new-property-name}: {COLUMN-PROPERTY}
            {COLUMN-PROPERTY}: __NULL__
```

Sorry if this isn't quite a "bug" or if issues with the mapper  belong somewhere else - it was not clear where communication / contribution streams are or go (and Slack is unfortunately blocked at my workplace).

### Code

```python
...
  mappers:
  - name: meltano-map-transformer
    variant: meltano
    pip_url: git+https://github.com/MeltanoLabs/meltano-map-transform.git
    mappings:
    - name: lower-case-schema
      config:
        stream_maps:
          {STREAM_NAME}:
            __alias__: {new-table-name}
            {COLUMN-PROPERTY}:
              __alias__: {new-property-name}
...
```
