### ISSUE TITLE
Cookiecutter template doesn't include the requests package

### ISSUE THREAD

**Issue by MeltyBot** [meltano/sdk#26]
Migrated from GitLab: https://gitlab.com/meltano/sdk/-/issues/26

Originally created by @edgarrmondragon on 2021-02-26 01:19:04

---

I just began exploring this awesome project and tried to create a tap for a simple REST API, however I found that the cookiecutter doesn't include `requests` in its dependencies:

```toml
[tool.poetry.dependencies]
python = "^3.6"
singer-python = "5.9.0"
singer-sdk = ">=0.0.0"
```
