### ISSUE TITLE
tech debt: Deprecate `Faker` in stream maps context and recommend `seed_instance`

### ISSUE THREAD

**Issue by edgarrmondragon** [meltano/sdk#2669]
Maybe I'm missing something, but could this not have been achieved already using `seed_instance`? 

```yml
stream_maps:
  customers:
    # will always generate the same value for the same seed
    first_name: fake.seed_instance(_['first_name']) or fake.first_name()
faker_config:
  # IMPORTANT: `fake` and `Faker` names are only available if faker_config is defined.
  locale: en_US
```

https://faker.readthedocs.io/en/master/index.html#seeding-the-generator

_Originally posted by @ReubenFrankel in https://github.com/meltano/sdk/issues/2598#issuecomment-2351217301_
