### ISSUE TITLE
feat: Make `len` avaiable in stream maps context

### ISSUE THREAD

**Issue by edgarrmondragon** [meltano/sdk#2680]
### Feature scope

Taps (catalog, state, stream maps, tests, etc.)

### Description

This could be useful to perform checks or compute new fields. It's currently not available, so something like this breaks:

```yaml
stream_maps:
  team:
     members_count: len(members)
```
