### ISSUE TITLE
feat: enable `load_schema` setting for sql targets

### ISSUE THREAD

**Issue by tobiascadee** [meltano/sdk#2950]
### Feature scope

Targets (data type handling, batching, SQL object generation, tests, etc.)

### Description

I'm a bit unsure whether to report this as a bug or feature, it depends if I'm just missing something.
The docs state that you can use the `load_schema` to set the schema in a (sql) target based on the setting in the tap. https://docs.meltano.com/concepts/plugins#load_schema-extra

However, if I look up the source code for the sql sink or connector I can't find the setting used anywhere. It seems like the schema name is defined using the `default_target_schema` setting or if the schema name is in a format like this `schema-name`. Would it be an option to add this or am I missing something?

**Comment by edgarrmondragon** [comment]
Hi @tobiascadee!

I think you're coming here from https://github.com/shaped-ai/target-clickhouse/issues/230?

The `default_target_schema` is append to SDK-based SQL targets by default and used here:

https://github.com/meltano/sdk/blob/868b5667cb1620e88efc561a74bc696d64e7f5b3/singer_sdk/sinks/sql.py#L87-L96

But `load_schema` is a Meltano _extra_ that is assigned a value of `$MELTANO_EXTRACTOR_NAMESPACE` at runtime, which translates to `tap_github`, for example.

That happens here: https://github.com/meltano/meltano/blob/e1905dcc1c0a5c4f4be4279ab745e626456b6e49/src/meltano/core/plugin/singer/tap.py#L176.

---

Now, I can confirm the `default_target_schema` setting is added to, for example, the Ticketswap Redshift and shaped-ai Clickhouse loaders:

```console
$ meltano --log-level=error config target-clickhouse list | grep default_target_schema
default_target_schema [env: TARGET_CLICKHOUSE_DEFAULT_TARGET_SCHEMA] current value: None (default)

$ meltano --log-level=error config target-redshift list | grep default_target_schema
default_target_schema [env: TARGET_REDSHIFT_DEFAULT_TARGET_SCHEMA] current value: None (default: '$MELTANO_EXTRACT__LOAD_SCHEMA')
```

You can see that Redshift correctly points to the Meltano extra but Clickhouse does not:

```yaml
# https://github.com/meltano/hub/blob/f084a7904897173a3f7a359482273484de5c26c7/_data/meltano/loaders/target-redshift/ticketswap.yml#L54-L58
- description: 'Redshift schema to send data to, example: tap-clickup'
  kind: string
  label: Default Target Schema
  name: default_target_schema
  value: $MELTANO_EXTRACT__LOAD_SCHEMA

# https://github.com/meltano/hub/blob/f084a7904897173a3f7a359482273484de5c26c7/_data/meltano/loaders/target-clickhouse/shaped-ai.yml#L41-L44
- description: The default target database schema name to use for all streams.
  kind: string
  label: Default Target Schema
  name: default_target_schema
```

And you could configure your own plugin to use `load_schema`:

```diff
# meltano.yml
plugins:
  loaders:
  - name: target-clickhouse
    config:
      database: $MELTANO_EXTRACT__LOAD_SCHEMA
```

It might make sense to update the Clickhouse definition to `load_schema` for the `database` setting, so that way tap-github would flow into the `tap_github` database:

```diff
# https://github.com/meltano/hub/blob/f084a7904897173a3f7a359482273484de5c26c7/_data/meltano/loaders/target-clickhouse/shaped-ai.yml#L36-L40
  - description: Database name
    kind: string
    label: Database
    name: database
+   value: $MELTANO_EXTRACT__LOAD_SCHEMA
```

That could not be what most users want though, so the per-case `config` approach seems preferable.

What do you think? I hope I didn't ramble to much 😅
