### ISSUE TITLE
[Feature]: Add `coverage` attribute to `--about` response object

### ISSUE THREAD

**Issue by kgpayne** [meltano/sdk#932]
### Feature scope

CLI (options, error messages, logging, etc.)

### Description

For users of taps evaluating a specific variant, source coverage is often an important metric used to inform their choice. Today, coverage information is not easy for tap builders to publish or for tap users to access. Coverage information is often omitted entirely (making it the users responsibility to inspect the taps streams or source) or is in free-text in the taps README. Adding a formalised `coverage` entity (and schema) as part of the SDKs' `--about` output would make coverage information i) publishable by tap maintainers, ii) discoverable by users and iii) scrapeable by Meltano Hub for rendering as part of the taps Hub page.

Something like (yaml form for readability):

```yaml
coverage:
# list of streams, corresponding to endpoints or entities available from the source
# only `stream` and `supported` fields required
# `endpoint` (or maybe a generic `extra` object field) might allow future automation to compare coverage to a swagger definition or similar
- stream: users
  supported: false
  endpoint: "/gmail/v1/users/{userId}/profile"
- stream: users.drafts
  supported: true
  endpoint: "/gmail/v1/users/{userId}/drafts"
- stream: users.history
  supported: true
  endpoint: "/gmail/v1/users/{userId}/history"
...
```
